namespace: plani-slack-bot
resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml

images:
  - name: harbor.plani.co.kr/plani-slack-bot/plani-slack-bot
    # CI 가 이 부분만 최신 태그로 교체 후 커밋
    newTag: "1.0.0"
