server:
  port: 8088

spring:
  profiles:
    active: dev
  application:
    name: plani-slack-bot

  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}

notion:
  api-key: ${NOTION_API_KEY}
  # notion 데이터베이스 아이디
  database:
    meeting-id: ${NOTION_MEETING}
    member-id: ${NOTION_MEMBER}
    document-id: ${NOTION_DOCUMENT}
    vacation-id: ${NOTION_VACATION}

slack:
  bot-token: ${SLACK_BOT_TOKEN}

logging:
  level:
    root: info
    org.springframework.web: error
